# Gestures config
bindgesture swipe:4:left workspace next
bindgesture swipe:4:right workspace prev

bindgesture swipe:4:up floating enabled
bindgesture swipe:4:down floating disabled

bindgesture hold:4 exec playerctl play-pause

bindgesture swipe:3:left move left 200px
bindgesture swipe:3:right move right 200px
bindgesture swipe:3:up move up 200px
bindgesture swipe:3:down move down 200px

