# workspaces stuff
assign [class="Spotify"] workspace 1
assign [app_id="ticktick"] workspace 1
assign [app_id="discord"] workspace 2
assign [app_id="zen"] workspace 3
# assign [app_id="neovide"] workspace 4
assign [app_id="STM32CubeIDE"] workspace 5
assign [class="com-st-microxplorer-maingui-STM32CubeMX"] workspace 6

# window rules
for_window {
  [app_id="zen"] inhibit_idle fullscreen
  [window_role="pop-up"] floating enable
  [window_role="bubble"] floating enable
  [window_role="dialog"] floating enable
  [window_type="dialog"] floating enable
  [app_id="blueman-manager"] floating enable
}
