# background
exec swaybg -o eDP-1 -i /home/joe/eye.jpg -m center
exec swaybg -o HDMI-A-1 -c '#000000' &

# policy kit
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# autorun programs 
exec_always waybar
exec_always nm-applet

# Idle configuration
exec swayidle -w \
         timeout 300 'swaylock -f -c 000000' \
         timeout 600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
         before-sleep 'swaylock -f -c 000000'

# opening applications 
exec zen-browser
exec discord
exec spotify-launcher
exec ticktick
