default_border none
default_floating_border none

# for stacking/tabbed layouts:
titlebar_border_thickness 0
titlebar_padding 0
font pango:monospace 8

mouse_warping container
corner_radius 15
gaps inner 5
gaps top 0

# colours
# 						border 	 bg	   text    indictr-o child border-o
client.focused 	#00000080 #000000 #000000 #00000080 #000000
client.unfocused 	#00000080 #000000 #000000 #00000080 #000000

# client.focused_inactive
# client.urgent
# client.background
