# changing prefix and stuff
unbind C-b
set-option -g prefix C-space
set -g mode-keys vi

# not quite sure what this line does 
bind-key C-space send-prefix

bind r source-file ~/.tmux.conf \; display "Config reloaded!"

set -sg escape-time 0

set -g base-index 1
setw -g pane-base-index 1

# copy mode
# Start selection with v
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Copy selection with y
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
