confirm_os_window_close 0

font_family JetBrainsMonoNerdFontMono
font_size 20.0

background #000000
background_opacity 0.4

cursor_trail 1
cursor_trail_start_threshold 0
cursor_trail_decay 0.1 0.3

# higher fps
repaint_delay 5
